<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GaifulinLab.Application\GaifulinLab.Application.csproj" />
    <ProjectReference Include="..\GaifulinLab.Contracts\GaifulinLab.Contracts.csproj" />
    <ProjectReference Include="..\GaifulinLab.Infrastructure\GaifulinLab.Infrastructure.csproj" />
    <ProjectReference Include="..\GaifulinLab.Web.Client\GaifulinLab.Web.Client.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.9" />
  </ItemGroup>

</Project>
