FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY . .
RUN dotnet restore src/GaifulinLab.PdfWorker/GaifulinLab.PdfWorker.csproj
RUN dotnet publish src/GaifulinLab.PdfWorker/GaifulinLab.PdfWorker.csproj -c Release -o /app/publish /p:UseAppHost=false

FROM node:22-bookworm-slim AS mathjax
WORKDIR /mathjax
RUN npm pack mathjax@4.1.3 \
    && tar -xzf mathjax-4.1.3.tgz \
    && mv package mathjax \
    && npm pack @mathjax/mathjax-newcm-font@4.1.3 \
    && tar -xzf mathjax-mathjax-newcm-font-4.1.3.tgz \
    && mv package mathjax-newcm-font

FROM mcr.microsoft.com/playwright/dotnet:v1.62.0-noble AS final
WORKDIR /app

COPY --from=build /app/publish .
COPY --from=mathjax /mathjax/mathjax /app/pdf-assets/mathjax
COPY --from=mathjax /mathjax/mathjax-newcm-font /app/pdf-assets/mathjax-newcm-font

ENTRYPOINT ["dotnet", "GaifulinLab.PdfWorker.dll"]
